###
get http://localhost:3001/api/persons

###

get http://localhost:3001/api/persons/646738ba624ced85f92b6480

#########

delete http://localhost:3001/api/persons/64673dbaa1e3c49beda96167

###

post http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "T1",
    "number": "12234562100"
}

